#!/bin/bash

for d in MDO/* 
do
    for e in $d/param.txt
    do
	if [ ! -f $d/done.txt ]
	then
            if [ ! -d $d/NOMAD-3.8.0.1.0/ ]
	    then
		mkdir $d/NOMAD-3.8.0.1.0
	    fi
	    echo "./NOMAD-3.8.0.1.0/bin/nomad $e >> $d/NOMAD-3.8.0.1.0/res.txt"
	    
	    ./NOMAD-3.8.0.1.0/bin/nomad $e >> $d/NOMAD-3.8.0.1.0/res.txt

            if [ ! -d $d/NOMAD-3.8.0.1.4/ ]
	    then
		mkdir $d/NOMAD-3.8.0.1.4
	    fi
	    echo "./NOMAD-3.8.0.1.4/bin/nomad $e >> $d/NOMAD-3.8.0.1.4/res.txt"
	    
	    ./NOMAD-3.8.0.1.4/bin/nomad $e >> $d/NOMAD-3.8.0.1.4/res.txt

            if [ ! -d $d/NOMAD-3.8.0.1.5/ ]
	    then
		mkdir $d/NOMAD-3.8.0.1.5
	    fi
	    echo "./NOMAD-3.8.0.1.5/bin/nomad $e >> $d/NOMAD-3.8.0.1.5/res.txt"
	    
	    ./NOMAD-3.8.0.1.5/bin/nomad $e >> $d/NOMAD-3.8.0.1.5/res.txt	    
            if [ ! -d $d/NOMAD-3.8.0.1.5/ ]
	    then
		mkdir $d/NOMAD-3.8.0.1.5
	    fi
	    echo "./NOMAD-3.8.0.1.5/bin/nomad $e >> $d/NOMAD-3.8.0.1.5/res.txt"
	    
	    ./NOMAD-3.8.0.1.5/bin/nomad $e >> $d/NOMAD-3.8.0.1.5/res.txt


	    if [ ! -d $d/NOMAD-3.8.0.1.6/ ]
	    then
		mkdir $d/NOMAD-3.8.0.1.6
	    fi
	    echo "./NOMAD-3.8.0.1.6/bin/nomad $e >> $d/NOMAD-3.8.0.1.6/res.txt"
	    
	    ./NOMAD-3.8.0.1.6/bin/nomad $e >> $d/NOMAD-3.8.0.1.6/res.txt

	    touch $d/done.txt

	    if [ ! -d $d/NOMAD-3.8.0.1.7/ ]
	    then
		mkdir $d/NOMAD-3.8.0.1.7
	    fi
	    echo "./NOMAD-3.8.0.1.7/bin/nomad $e >> $d/NOMAD-3.8.0.1.7/res.txt"
	    
	    ./NOMAD-3.8.0.1.7/bin/nomad $e >> $d/NOMAD-3.8.0.1.7/res.txt

	    touch $d/done.txt

	    if [ ! -d $d/NOMAD-3.8.0.1.8/ ]
	    then
		mkdir $d/NOMAD-3.8.0.1.8
	    fi
	    echo "./NOMAD-3.8.0.1.8/bin/nomad $e >> $d/NOMAD-3.8.0.1.8/res.txt"
	    
	    ./NOMAD-3.8.0.1.8/bin/nomad $e >> $d/NOMAD-3.8.0.1.8/res.txt

	    touch $d/done.txt

	    if [ ! -d $d/NOMAD-3.8.0.1.9/ ]
	    then
		mkdir $d/NOMAD-3.8.0.1.9
	    fi
	    echo "./NOMAD-3.8.0.1.9/bin/nomad $e >> $d/NOMAD-3.8.0.1.9/res.txt"
	    
	    ./NOMAD-3.8.0.1.9/bin/nomad $e >> $d/NOMAD-3.8.0.1.9/res.txt

	    touch $d/done.txt

	    if [ ! -d $d/NOMAD-3.8.0.1.13/ ]
	    then
		mkdir $d/NOMAD-3.8.0.1.13
	    fi
	    echo "./NOMAD-3.8.0.1.13/bin/nomad $e >> $d/NOMAD-3.8.0.1.13/res.txt"
	    
	    ./NOMAD-3.8.0.1.13/bin/nomad $e >> $d/NOMAD-3.8.0.1.13/res.txt

	    touch $d/done.txt
	fi
    done
done

